<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WarehouseManager.Application\WarehouseManager.Application.csproj" />
		<ProjectReference Include="..\WarehouseManager.Infrastructure\WarehouseManager.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Converters\" />
	  <Folder Include="Behaviors\" />
	  <Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<None
			Update="appsettings.json">
			<CopyToOutputDirectory>
				PreserveNewest
			</CopyToOutputDirectory>
		</None>

	</ItemGroup>

</Project>
